# Generated by Django 6.0.4 on 2026-04-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department_head', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader', models.CharField(blank=True, max_length=100)),
                ('jira_project_name', models.CharField(blank=True, max_length=150)),
                ('github_repo', models.CharField(blank=True, max_length=200)),
                ('focus_areas', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('downstream_dependencies', models.TextField(blank=True)),
                ('dependency_type', models.CharField(blank=True, max_length=100)),
                ('slack_channels', models.TextField(blank=True)),
                ('team_wiki', models.CharField(blank=True, max_length=200)),
                ('concurrent_projects', models.CharField(blank=True, max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.department')),
            ],
        ),
    ]
